baseURL = "http://harsha.ca/"
languageCode = "en-us"
title = "harsha.ca"
theme = "hello-friend-ng"
staticDir = ["Resume"]

# Social icons
[[params.social]]
    name = "twitter"
    url  = "https://twitter.com/devkhv129"

[[params.social]]
    name = "email"
    url  = "mailto:devkhv129@gmail.com"

[[params.social]]
    name = "github"
    url  = "https://github.com/asystemsguy"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/devkhv129/"

[[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4425037/harsha"


[params]
  dateform        = "October 2, 2019"
  dateformShort   = "Oct 2"
  dateformNum     = "2019-01-02"
  dateformNumTime = "2019-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by harsha"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Harshavardhan Kadiyala"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "A systems guy"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "pubkey"
    name       = "Public key"
    url        = "https://keybase.io/devkhv129/pgp_keys.asc"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "resume.pdf" 
