baseURL = "http://harsha.ca/"
languageCode = "en-us"
title = "harsha.ca"
theme = "hello-friend-ng"

[params]
  dateform        = "October 2, 2019"
  dateformShort   = "Oct 2"
  dateformNum     = "2019-01-02"
  dateformNumTime = "2019-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by harsha"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Harshavardhan Kadiyala"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "harsha"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "resume" 
